---
- hosts: dev
  connection: ssh
  tasks:
    - name: Install Git on dev server
      yum:
        name: git
        state: present

    - name: Install Java 1.8 OpenJDK on dev server
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Install Maven on dev server
      yum:
        name: maven
        state: present

- hosts: test
  connection: ssh
  tasks:
    - name: Install Git on test server
      yum:
        name: git
        state: present

    - name: Install Java 1.8 OpenJDK on test server
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Install Maven on test server
      yum:
        name: maven
        state: present
...
