---

   - hosts: dev
    connection: ssh

    tasks:
      - name: install git
        yum:
          name: git
          state: present

      - name: get code from github
        git: 
         repo: "https://mdsurem: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@github.com/MdSurem/Script-Files.git"
         dest: "mdsurem"
         update: yes


         #### private repo ###
         #"https://yourusername:yourtoken@github.com/MdSurem/Script-Files.git"#
