---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ola
  template:
    metadata:
      labels:
        app: ola
    spec:
      containers:
        - name: cont-1
          image: mdsurem/html:nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: devops
              mountPath: "/var/jenkins"

      volumes:
         - name: devops
           persistentVolumeClaim:
             claimName: pvc-1



---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  type: NodePort
  selector:
    app: ola
  ports:
    - port: 80
      targetPort: 80
