---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uber
  template:
    metadata:
      labels:
        app: uber
    spec:
      containers:
        - name: cont-1
          image: mdsurem/html:nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: devops
              mountPath: "/app/nginx/surem"
      volumes:
        - name: devops
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  selector:
    app: uber
  ports:
    - port: 80
      targetPort: 80

