---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: cont-2
          image: httpd
          ports:
            - containerPort: 80
          volumeMounts:
            - name: course
              mountPath: "/app/bin/local/"
      volumes:
        - name: course
          hostPath:
             path: "/temp/share/httpd"

---
apiVersion: v1
kind: Service
metadata:
  name: svc-2
spec:
  type: NodePort
  selector:
    app: zomato
  ports:
    - port: 80
      targetPort: 80
