- hosts: dev
  connection: ssh

  tasks:
     - name: install git
       yum:
         name: git
         state: present

     - name: install java-1.8
       yum:
         name: java-1.8.0-openjdk
         state: present

     - name: install httped web server
       yum:
         name: httpd
         state: present

     - name: start the httpd
       service:
           name: httpd
           state: started

     - name: craere folder
       file:
          path: "var/www/html"
          state: directory

     - name: create a file
       file:
          path: "/var/www/html/index.html"
          state: touch

     - name: content of the file
       copy:
         dest: "/var/www/html/index.html"
          content: |
            <h1 class="restaurant-name">MDSUREM ALWAYS WELCOME</h1>
            <h1 class="slogan">NO MONEY, NO FEAR, COME INSIDE, EAT SOMETHING!</h1>
            <h1 class="slogan">We are successfully deployed web server through Ansible -playbook!</h1>


     - name: create some folders
       file:
          path: "devops/Aws/Azure/Gcp"
          state: directory

     - name: install tree package
       yum:
          name: tree
          state: present
