---

- hosts: dev
  connection: ssh
  tasks:
    - name: create users
      user:
        name: "{{ item }}"
        state: present      ##if you want to delete the user change state as "absent"
      loop:
        - renuka
        - Alvin
        - Robin
        - Ayesha
