---

 - hosts: dev
   connection: ssh

   tasks:
     - name: installing webserver
       yum:
         name: httpd
         state: present
       when: ansible_os_family == "RedHat"

     - name: installing webserver
       apt:
         name: apache2
         state: present
       when: ansible_os_family == "Ubuntu"

...
