---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont-1
          image: mdsurem/demo:httpd
          ports:
            - containerPort: 80
          volumeMounts:
            - name: devops
              mountPath: "/opt/jenkins"
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: docker-hub-secret
      volumes:
        - name: devops
          hostPath:
            path: "/var/volume"


---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  type: NodePort
  selector:
    app: swiggy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007

